version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - ${MONGO_PORT}:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/todoapp --quiet
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
        

  todo-backend:
    image: todo-backend
    build: 
      context: ./todo-backend
      dockerfile: Dockerfile
    ports:
      - ${TODO_BACKEND_PORT}:8000
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
  
  todo-frontend:
    image: todo-frontend
    build: 
      context: ./todo-frontend
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL}
    ports:
      - ${TODO_FRONTEND_PORT}:3000
    depends_on:
      - todo-backend
